    function applyPrefs(){const size=Math.max(12,Math.min(24,Number(prefs.fontSize)||14)); prefs.fontSize=size; document.body.style.setProperty("--message-font-size",`${size}px`); document.body.classList.toggle("dark",!!prefs.dark); fontSize.value=String(size); fontSizeValue.value=`${size}px`; themeBtn.textContent=prefs.dark?"日间":"暗夜"; document.getElementById("resetToCover").checked=prefs.resetToCover!==false; const showAll=document.getElementById("showAllPrivateRooms"); if(showAll)showAll.checked=!!prefs.showAllPrivateRooms; const showArrival=document.getElementById("showArrivalOnEnter"); if(showArrival)showArrival.checked=!!prefs.showArrivalOnEnter;}
    let _renderChatSeq=0;
    const VIRTUAL_CHAT_THRESHOLD=300;
    const VIRTUAL_CHAT_ITEM_ESTIMATE=96;
    const VIRTUAL_CHAT_OVERSCAN=20;
    const VIRTUAL_CHAT_MIN_RENDER=60;
    const VIRTUAL_CHAT_MAX_RENDER=180;
    const chatVirtualState={roomId:"",scrollTop:0,viewportHeight:0,total:0,start:0,end:0,itemEstimate:VIRTUAL_CHAT_ITEM_ESTIMATE,enabled:false,pendingScrollToBottom:false,listenerBound:false,scrollRaf:0,windowSeq:0,suppressScroll:false};
    async function resolveStoredImageUrl(record,idKey,dataKey){
      if(record?.[idKey]){
        try{
          const url=await window.imageStore?.getImageUrl(record[idKey]);
          if(url)return url;
          console.warn("stored image missing",idKey,record[idKey]);
        }catch(err){
          console.warn("stored image resolve failed",idKey,record[idKey],err);
        }
      }
      return record?.[dataKey]||"";
    }
    async function buildStoredImageUrlMap(records,idKey,dataKey){
      const map=new Map(), byImageId=new Map();
      (records||[]).forEach(record=>{if(record?.[idKey]){if(!byImageId.has(record[idKey]))byImageId.set(record[idKey],[]); byImageId.get(record[idKey]).push(record);} else if(record?.[dataKey]){map.set(record.id,record[dataKey]);}});
      await Promise.all([...byImageId.entries()].map(async([imageId,items])=>{const url=await resolveStoredImageUrl(items[0],idKey,dataKey); items.forEach(record=>map.set(record.id,url)); map.set(imageId,url);}));
      return map;
    }
    function avatarContent(name,src){return src?`<img src="${esc(src)}" alt="${esc(name||"头像")}" />`:esc(first(name));}
    function tagDot(tagId,extra=""){const t=tag(tagId); return t?`<i class="tag-dot ${extra}" style="background:${esc(t.color)}" title="${esc(t.name)}"></i>`:"";}
    function tagName(tagId){return tag(tagId)?.name||"无标签";}
    /* ── 视角与可见性 ── */
    function currentViewMember(){return prefs.currentViewMemberId?member(prefs.currentViewMemberId):null;}
    function isRoomVisibleInView(r){if(!isPrivateRoom(r))return true; if(prefs.showAllPrivateRooms)return true; const vm=currentViewMember(); if(!vm)return false; return (r.memberIds||[]).includes(vm.id);}
    function visibleRoomMatchesSearch(r,q){if(!q)return true; const names=(r.memberIds||[]).map(id=>member(id)?.name||"").join(" "); return (roomDisplayName(r)+" "+roomDisplayDesc(r)+" "+names).toLowerCase().includes(q);}
    function memberMatchesSearch(m,q){if(!q)return true; const aliases=normalizeMemberAliasesInput(m.aliases).join(" "); const custom=(Array.isArray(m.customFields)?m.customFields:[]).map(f=>`${f?.name||""} ${f?.value||""}`).join(" "); const text=[m.name,m.role,statusText(m.status),tagName(m.tagId),m.note,m.pronouns,aliases,m.comfortMethods,m.boundaries,m.avoidNotes,m.communicationStyle,m.frontingPreferences,custom].map(v=>String(v||"")).join(" ").toLowerCase(); return text.includes(q);}
    function renderViewSelector(){const sel=document.getElementById("viewSelect"); if(!sel)return; const current=prefs.currentViewMemberId||""; const exists=!current||data.members.some(m=>m.id===current); if(!exists){prefs.currentViewMemberId=""; safeSavePrefs("修正视角设置");} sel.innerHTML=[`<option value="">全${esc(term("system"))}</option>`,...data.members.map(m=>{const tail=m.status==="gone"?"（已消失）":m.status==="resting"?"（休眠）":m.status==="unknown"?"（不确定）":""; return `<option value="${esc(m.id)}">${esc(m.name)}${esc(tail)}</option>`;})].join(""); sel.value=prefs.currentViewMemberId||"";}
    function renderFrontingStatus(){
      const current=typeof getCurrentFrontingLog==="function"?getCurrentFrontingLog():(typeof currentFrontingLog==="function"?currentFrontingLog():null);
      const btn=document.getElementById("frontingBtn");
      if(!btn)return;
      if(!current){btn.textContent=term("fronting"); return;}
      const ids=Array.isArray(current.memberIds)?current.memberIds:[];
      const primary=current.primaryMemberId&&ids.includes(current.primaryMemberId)?current.primaryMemberId:null;
      const findName=id=>data.members.find(m=>m.id===id)?.name||"已移除";
      const ordered=primary?[primary,...ids.filter(id=>id!==primary)]:ids;
      const shortNames=()=>{const names=ordered.slice(0,2).map(findName).join(" / "); return ordered.length>2?`${names} 等`:names;};
      const state=current.stateType||"front";
      if(state==="unknown"){btn.textContent=`${term("fronting")}不确定`; return;}
      if(state==="blended"){btn.textContent=ids.length?`混合：${shortNames()}`:"混合状态"; return;}
      if(state==="cofront"){btn.textContent=ids.length?`${term("cofronting")}：${shortNames()}`:term("cofronting"); return;}
      if(state==="near"){btn.textContent=ids.length?`靠近${term("fronting")}：${shortNames()}`:`靠近${term("fronting")}`; return;}
      if(state==="observer"){btn.textContent=ids.length?`在场：${shortNames()}`:"在场"; return;}
      if(!ids.length){btn.textContent=`${term("fronting")}未记录${term("member")}`; return;}
      if(ids.length===1){btn.textContent=`${findName(ids[0])} 在前`; return;}
      if(primary){btn.textContent=`${findName(primary)} 在前 · ${ids.length}人在场`; return;}
      btn.textContent=`${findName(ids[0])} 等在前`;
    }
    async function render(){try{renderViewSelector(); await renderList(); renderSpeaker(); renderKindOptions(); await renderChat(); renderPolls(); renderHandoff(); renderSystemProfile(); renderRelations(); await renderStructureView(); renderSystemCardPanel(); renderFrontingStatus(); if(typeof applyTermsToStaticLabels==="function")applyTermsToStaticLabels();}catch(err){console.error("render failed",err);}}
    function safeRender(){return Promise.resolve(render()).catch(err=>console.error("render failed",err));}
    async function renderList(){try{const q=search.value.trim().toLowerCase(); if(tab==="rooms"||tab==="private"){const wantPrivate=tab==="private"; let rooms=data.rooms.filter(r=>isPrivateRoom(r)===wantPrivate); if(wantPrivate)rooms=rooms.filter(isRoomVisibleInView); rooms=rooms.filter(r=>visibleRoomMatchesSearch(r,q)); const vm=currentViewMember(); const emptyHint=wantPrivate?(prefs.showAllPrivateRooms?`没有${term("privateRoom")} / 小群聊`:vm?`「${vm.name}」视角下没有可见的${term("privateRoom")} / 小群聊`:`全${term("system")}视角默认不显示${term("privateRoom")}。切换到某位${term("member")}或在设置里开启「管理模式」可见。`):`没有${term("room")}`; list.innerHTML=rooms.length?rooms.map(r=>{const last=data.messages.filter(m=>m.roomId===r.id).slice(-1)[0]; const type=isPrivateRoom(r)?"private":"room"; const badge=isPrivateRoom(r)?(privateNoun(r)==="小群聊"?"群":"私"):first(roomDisplayName(r)); return `<div class="item ${r.id===currentRoomId?"active":""}" onclick="selectRoom('${r.id}')" oncontextmenu="showRoomMenu(event,'${r.id}')" onpointerdown="startLongPress(event,'${type}','${r.id}')" onpointerup="cancelLongPress()" onpointercancel="cancelLongPress()" onpointerleave="cancelLongPress()"><div class="avatar">${badge}</div><div class="meta"><strong>${esc(roomDisplayName(r))}</strong><span>${esc(last?messageText(last):roomDisplayDesc(r))}</span></div></div>`}).join(""):`<div class="empty">${esc(emptyHint)}</div>`;} else {const members=data.members.filter(m=>memberMatchesSearch(m,q)); const avatarUrlMap=await buildStoredImageUrlMap(members,"avatarId","avatarData"); list.innerHTML=members.length?members.map(m=>`<div class="item" oncontextmenu="showMemberMenu(event,'${m.id}')" onpointerdown="startLongPress(event,'member','${m.id}')" onpointerup="cancelLongPress()" onpointercancel="cancelLongPress()" onpointerleave="cancelLongPress()">${tagDot(m.tagId,"member-tag")}<div class="avatar">${avatarContent(m.name,avatarUrlMap.get(m.id)||"")}</div><div class="meta"><strong>${esc(m.name)}</strong><span><i class="status-dot ${statusClass(m.status)}"></i>${esc(statusText(m.status))} · ${esc(tagName(m.tagId))} · ${esc(m.role||"未填写角色")}</span></div></div>`).join(""):`<div class="empty">没有${esc(term("member"))}</div>`;}}catch(err){console.error("renderList failed",err);}}
    function clampChatVirtualValue(value,min,max){return Math.max(min,Math.min(max,value));}
    function getRoomMessages(roomId=currentRoomId){return (data.messages||[]).filter(m=>m.roomId===roomId);}
    function getCurrentRoomMessages(){return getRoomMessages(currentRoomId);}
    function getMessageIndexInCurrentRoom(messageId){const id=String(messageId||""); if(!id)return -1; return getCurrentRoomMessages().findIndex(m=>String(m.id)===id);}
    function applyChatBackground(bgUrl){messages.style.backgroundImage=bgUrl?`url("${bgUrl}")`:""; messages.classList.toggle("has-bg",!!bgUrl);}
    function cancelChatVirtualScrollFrame(){if(chatVirtualState.scrollRaf){cancelAnimationFrame(chatVirtualState.scrollRaf); chatVirtualState.scrollRaf=0;}}
    function releaseChatVirtualScrollSuppression(){const release=()=>{chatVirtualState.suppressScroll=false;}; if(typeof requestAnimationFrame==="function")requestAnimationFrame(release); else setTimeout(release,0);}
    function markChatShouldScrollToBottom(){chatVirtualState.pendingScrollToBottom=true; if(window._pendingSearchHitMessageId)window._pendingSearchHitMessageId="";}
    function scrollChatToBottom(){if(!messages)return; messages.scrollTop=messages.scrollHeight; chatVirtualState.scrollTop=messages.scrollTop;}
    function renderMessageBubble(m,i,rows,messageImageUrlMap,avatarUrlMap,activeSpeakerId){const name=memberNameByMessage(m); const person=member(m.speakerId); const isSystem=m.speakerId==="system"; const mine=!isSystem&&m.speakerId===activeSpeakerId; const ok=integrityOk(m); const imageUrl=messageImageUrlMap.get(m.id)||messageImageUrlMap.get(m.imageId)||""; const avatarUrl=person?(avatarUrlMap.get(person.id)||""):""; const showTime=i===0||new Date(m.createdAt)-new Date(rows[i-1].createdAt)>600000; const hitId=String(window._pendingSearchHitMessageId||""); const msgClasses=["msg",isSystem?"system":mine?"mine":"",hitId&&hitId===String(m.id)?"search-hit-flash":""].filter(Boolean).join(" "); return `${showTime?`<div class="time">${new Date(m.createdAt).toLocaleString()}</div>`:""}<div class="${msgClasses}" data-message-id="${esc(m.id)}" oncontextmenu="showMessageMenu(event,'${m.id}')" onpointerdown="startLongPress(event,'message','${m.id}')" onpointerup="cancelLongPress()" onpointercancel="cancelLongPress()" onpointerleave="cancelLongPress()"><div class="mini">${avatarContent(name,avatarUrl)}</div><div class="bubble-wrap"><div class="who">${tagDot(person?.tagId)}${esc(name)} · ${esc(m.kind)}</div><div class="bubble">${bubbleContent(m,imageUrl)}</div><div class="msg-id ${ok?"":"bad"}">校验码 ${esc(seqCode(m))} · ${ok?"校验正常":"校验异常"}</div></div></div>`;}
    async function renderChatRows(rows,start,end,activeSpeakerId){const slice=rows.slice(start,end); const people=slice.map(m=>member(m.speakerId)).filter(Boolean); const [messageImageUrlMap,avatarUrlMap]=await Promise.all([buildStoredImageUrlMap(slice,"imageId","imageData"),buildStoredImageUrlMap(people,"avatarId","avatarData")]); return slice.map((m,i)=>renderMessageBubble(m,start+i,rows,messageImageUrlMap,avatarUrlMap,activeSpeakerId)).join("");}
    function ensureChatVirtualScrollListener(){if(chatVirtualState.listenerBound||!messages)return; messages.addEventListener("scroll",()=>{if(!chatVirtualState.enabled)return; chatVirtualState.scrollTop=messages.scrollTop; if(chatVirtualState.suppressScroll)return; if(chatVirtualState.scrollRaf)return; chatVirtualState.scrollRaf=requestAnimationFrame(()=>{chatVirtualState.scrollRaf=0; if(chatVirtualState.enabled)renderChatVirtualWindow(_renderChatSeq,getCurrentRoomMessages(),{preserveScroll:true});});},{passive:true}); chatVirtualState.listenerBound=true;}
    async function renderChatVirtualWindow(seq,rows=getCurrentRoomMessages(),options={}){const windowSeq=++chatVirtualState.windowSeq; try{const total=rows.length; if(!messages||!total)return; const activeSpeakerId=speaker.value||data.members[0]?.id; const viewportHeight=Math.max(messages.clientHeight||0,VIRTUAL_CHAT_ITEM_ESTIMATE*3); const estimate=Math.max(48,Number(chatVirtualState.itemEstimate)||VIRTUAL_CHAT_ITEM_ESTIMATE); const minCount=Math.min(total,VIRTUAL_CHAT_MIN_RENDER); const visibleCount=Math.ceil(viewportHeight/estimate)+VIRTUAL_CHAT_OVERSCAN*2; const count=Math.min(total,VIRTUAL_CHAT_MAX_RENDER,Math.max(minCount,visibleCount)); const maxStart=Math.max(0,total-count); const targetMessageId=String(options.targetMessageId||""); const targetIndex=targetMessageId?rows.findIndex(m=>String(m.id)===targetMessageId):-1; let start;if(targetIndex>=0){start=clampChatVirtualValue(targetIndex-Math.floor(count/2),0,maxStart);}else if(options.scrollToBottom){start=maxStart;}else{const scrollTop=Number(options.scrollTop??messages.scrollTop)||0; start=clampChatVirtualValue(Math.floor(scrollTop/estimate)-VIRTUAL_CHAT_OVERSCAN,0,maxStart);} const end=Math.min(total,start+count); const html=await renderChatRows(rows,start,end,activeSpeakerId); if(seq!==_renderChatSeq||windowSeq!==chatVirtualState.windowSeq)return; const topHeight=Math.max(0,Math.round(start*estimate)); const bottomHeight=Math.max(0,Math.round((total-end)*estimate)); cancelChatVirtualScrollFrame(); chatVirtualState.suppressScroll=true; messages.classList.add("virtualized"); messages.innerHTML=`<div class="chat-virtual-spacer top" style="height:${topHeight}px"></div><div class="chat-virtual-list">${html}</div><div class="chat-virtual-spacer bottom" style="height:${bottomHeight}px"></div>`; chatVirtualState.enabled=true; chatVirtualState.roomId=currentRoomId; chatVirtualState.viewportHeight=viewportHeight; chatVirtualState.total=total; chatVirtualState.start=start; chatVirtualState.end=end; const listEl=messages.querySelector(".chat-virtual-list"); const measured=listEl&&end>start?listEl.offsetHeight/(end-start):0; if(Number.isFinite(measured)&&measured>=48&&measured<=280)chatVirtualState.itemEstimate=Math.round(chatVirtualState.itemEstimate*.8+measured*.2); if(targetIndex>=0){const targetTop=targetIndex*estimate-viewportHeight/2+estimate/2; messages.scrollTop=clampChatVirtualValue(targetTop,0,Math.max(0,messages.scrollHeight-viewportHeight));}else if(options.scrollToBottom){scrollChatToBottom();}else if(options.preserveScroll){messages.scrollTop=chatVirtualState.scrollTop;} chatVirtualState.scrollTop=messages.scrollTop; releaseChatVirtualScrollSuppression();}catch(err){chatVirtualState.suppressScroll=false; console.error("renderChatVirtualWindow failed",err);}}
    async function scrollVirtualChatToMessage(messageId){const id=String(messageId||""); if(!id)return false; const rows=getCurrentRoomMessages(); const index=rows.findIndex(m=>String(m.id)===id); if(index<0)return false; if(rows.length<=VIRTUAL_CHAT_THRESHOLD){return !!document.querySelector(`.msg[data-message-id="${id.replace(/\\/g,"\\\\").replace(/"/g,'\\"')}"]`);} cancelChatVirtualScrollFrame(); await renderChatVirtualWindow(_renderChatSeq,rows,{targetMessageId:id}); return true;}
    async function renderChat(){const seq=++_renderChatSeq; try{const r=room(); if(!r)return; ensureChatVirtualScrollListener(); cancelChatVirtualScrollFrame(); roomName.textContent=roomDisplayName(r); roomDesc.textContent=roomDisplayDesc(r); const rows=getRoomMessages(r.id); const bgUrl=await resolveStoredImageUrl(r,"backgroundId","backgroundData"); if(seq!==_renderChatSeq)return; applyChatBackground(bgUrl); if(chatVirtualState.roomId!==r.id){chatVirtualState.roomId=r.id; chatVirtualState.scrollTop=0; chatVirtualState.itemEstimate=VIRTUAL_CHAT_ITEM_ESTIMATE;} if(!rows.length){chatVirtualState.enabled=false; chatVirtualState.total=0; chatVirtualState.start=0; chatVirtualState.end=0; messages.classList.remove("virtualized"); messages.innerHTML='<div class="empty">还没有记录。</div>';return;} const pendingHit=String(window._pendingSearchHitMessageId||""); const pendingHitInRoom=pendingHit&&rows.some(m=>String(m.id)===pendingHit); const forceBottom=!!chatVirtualState.pendingScrollToBottom; const schedulePendingHit=()=>{if(pendingHitInRoom&&!forceBottom&&typeof window.highlightSearchHitMessage==="function")setTimeout(()=>{if(window._pendingSearchHitMessageId===pendingHit)window.highlightSearchHitMessage(pendingHit);},0);}; if(rows.length<=VIRTUAL_CHAT_THRESHOLD){chatVirtualState.enabled=false; chatVirtualState.total=rows.length; chatVirtualState.start=0; chatVirtualState.end=rows.length; messages.classList.remove("virtualized"); const activeSpeakerId=speaker.value||data.members[0]?.id; const html=await renderChatRows(rows,0,rows.length,activeSpeakerId); if(seq!==_renderChatSeq)return; messages.innerHTML=html; scrollChatToBottom(); chatVirtualState.pendingScrollToBottom=false; schedulePendingHit(); return;} await renderChatVirtualWindow(seq,rows,{targetMessageId:pendingHitInRoom&&!forceBottom?pendingHit:"",scrollToBottom:forceBottom||!pendingHitInRoom}); chatVirtualState.pendingScrollToBottom=false; schedulePendingHit();}catch(err){console.error("renderChat failed",err);}}
    window.getCurrentRoomMessages=getCurrentRoomMessages;
    window.getMessageIndexInCurrentRoom=getMessageIndexInCurrentRoom;
    window.scrollVirtualChatToMessage=scrollVirtualChatToMessage;
    window.markChatShouldScrollToBottom=markChatShouldScrollToBottom;
    window.scrollChatToBottom=scrollChatToBottom;
    function renderSpeaker(){const current=speaker.value; const r=room(); let available; if(isPrivateRoom(r)){const ids=new Set(r.memberIds||[]); available=data.members.filter(m=>ids.has(m.id));} else {available=data.members.filter(m=>m.status!=="gone");} if(!available.length){speaker.innerHTML='<option value="">无可用成员</option>'; return;} speaker.innerHTML=available.map(m=>{const isGone=m.status==="gone"; const tagPart=tag(m.tagId)?`【${tagName(m.tagId)}】`:""; const statusPart=isGone?"（暂不可联系）":m.status==="resting"?"（休眠）":m.status==="unknown"?"（不确定）":""; return `<option value="${esc(m.id)}" ${isGone?"disabled":""}>${esc(tagPart)}${esc(m.name)}${esc(statusPart)}</option>`;}).join(""); const enabled=available.filter(m=>m.status!=="gone"); const fallback=enabled[0]?.id||""; if(current&&available.some(m=>m.id===current&&m.status!=="gone"))speaker.value=current; else speaker.value=fallback;}
    function renderKindOptions(selected=kind.value){const kinds=data.messageKinds?.length?data.messageKinds:DEFAULT_KINDS; kind.innerHTML=kinds.map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join(""); kind.value=kinds.includes(selected)?selected:kinds[0]; renderKindManager();}
    function renderKindManager(){const box=document.getElementById("kindList"); if(!box)return; const selected=kind.value; const kinds=data.messageKinds?.length?data.messageKinds:DEFAULT_KINDS; box.innerHTML=kinds.map(k=>{const key=encodeURIComponent(k); return `<div class="kind-row"><strong>${esc(k)}</strong><button class="light small" type="button" onclick="selectKindForEdit('${key}')">选择</button><button class="danger small" type="button" onclick="deleteKind('${key}')">删除</button></div>`;}).join(""); if(selected)document.getElementById("kindName").value=selected;}
    function normalizeKindName(value){return String(value||"").trim().replace(/\s+/g," ").slice(0,20);}
    function decodeKindName(value){try{return decodeURIComponent(value);}catch{return value;}}
    window.selectKindForEdit=function(name){name=decodeKindName(name); kind.value=name; document.getElementById("kindName").value=name; renderKindManager();};
    async function saveKind(){const name=normalizeKindName(document.getElementById("kindName").value); if(!name){alert("请先填写分类名称。");return;} data.messageKinds=data.messageKinds?.length?data.messageKinds:[]; const old=kind.value; const index=data.messageKinds.indexOf(old); if(index>=0&&old!==name){data.messageKinds[index]=name;} else if(!data.messageKinds.includes(name)){data.messageKinds.push(name);} data.messageKinds=[...new Set(data.messageKinds.map(normalizeKindName).filter(Boolean))]; if(await save())renderKindOptions(name);}
    window.deleteKind=async function(name=kind.value){const target=normalizeKindName(decodeKindName(name)); if(!target)return; if(!confirm(`确定删除分类「${target}」吗？\n\n历史记录不会被删除，会保留原来的分类文字。`))return; data.messageKinds=(data.messageKinds||[]).filter(k=>k!==target); if(!data.messageKinds.length)data.messageKinds=["普通"]; if(await save())renderKindOptions(data.messageKinds[0]);};
