    const HANDOFF_TEMPLATES={
      blank:"",
      sleep:"- 现在在哪里：\n- 身体状态：\n- 今天还没完成：\n- 明天需要记得：\n- 不要忘记：\n- 给醒来后前台的话：",
      outside:"- 现在要去哪里：\n- 身上需要带：\n- 已确认事项：\n- 路上需要注意：\n- 回来后要做：\n- 给后来前台的话：",
      work:"- 当前任务：\n- 已完成：\n- 还需要做：\n- 重要资料 / 链接：\n- 截止时间：\n- 给接手者的话：",
      intense:"- 刚刚发生了什么：\n- 现在身体状态：\n- 现在比较安全的做法：\n- 需要避免：\n- 可以安抚的方式：\n- 给后来前台的话：",
      fronting:"- 刚刚是谁在前：\n- 现在发生到哪一步：\n- 接下来要做：\n- 需要记得的人 / 事：\n- 不确定的地方：\n- 给接手者的话：",
      target:"- 想留言给：\n- 这件事是：\n- 希望你知道：\n- 需要你决定 / 处理：\n- 不急的部分：\n- 留言："
    };
    function appendHandoff(text,source="手动便签",roomId=currentRoomId){data.handoffNotes=data.handoffNotes||[]; const note={id:makeId(),roomId,source,text,createdAt:now()}; data.handoffNotes.push(note); return note;}
    function renderHandoff(){const box=document.getElementById("handoffList"); if(!box)return; const notes=(data.handoffNotes||[]).filter(n=>n.roomId===currentRoomId).slice().reverse(); box.innerHTML=notes.length?notes.map(n=>`<div class="handoff-card"><strong>${esc(new Date(n.createdAt).toLocaleString())} · ${esc(n.source||"交接")}</strong><p>${esc(n.text)}</p></div>`).join(""):'<div class="empty">当前群组还没有交接便签。</div>'; if(typeof window.renderTasks==="function")window.renderTasks();}
    function applyHandoffTemplate(){const select=document.getElementById("handoffTemplate"); const area=document.getElementById("handoffText"); if(!select||!area)return; const nextKey=select.value||"blank"; const previousKey=select.dataset.currentTemplate||"blank"; const nextText=HANDOFF_TEMPLATES[nextKey]||""; if(area.value.trim()&&area.value!==nextText&&!confirm("当前交接内容会被模板替换，继续吗？")){select.value=previousKey; return;} area.value=nextText; select.dataset.currentTemplate=nextKey;}
    function openHandoffModal(){renderHandoff(); if(typeof window.renderTaskMemberPicker==="function")window.renderTaskMemberPicker(); if(typeof window.resetHandoffTaskForm==="function")window.resetHandoffTaskForm(); const template=document.getElementById("handoffTemplate"); if(template){template.value="blank"; template.dataset.currentTemplate="blank";} if(typeof openModal==="function")openModal("handoffModal"); else document.getElementById("handoffModal").style.display="flex";}
    async function saveManualHandoff(){const text=document.getElementById("handoffText").value.trim(); if(!text){alert("请先填写便签内容。");return;} const createChecked=!!document.getElementById("handoffCreateTask")?.checked; const taskTitleEl=document.getElementById("handoffTaskTitle"); const taskDetailEl=document.getElementById("handoffTaskDetail"); const taskDueEl=document.getElementById("handoffTaskDueAt"); const note=appendHandoff(text,"手动便签"); if(createChecked){const detail=taskDetailEl?.value.trim()||""; const fallback=detail||text; const title=(taskTitleEl?.value.trim()||fallback.slice(0,20)).trim(); if(!title){alert("请填写任务标题。");return;} if(typeof window.createTask==="function"){window.createTask({title,detail,status:"todo",assignedMemberIds:typeof window.collectTaskAssignedMemberIds==="function"?window.collectTaskAssignedMemberIds("handoffTaskMemberPicker"):[],dueAt:taskDueEl?.value||"",source:"handoff",linkedHandoffId:note.id});} else {alert("任务模块还没有准备好，本次只保存交接。");}} if(!(await save()))return; document.getElementById("handoffText").value=""; const template=document.getElementById("handoffTemplate"); if(template){template.value="blank"; template.dataset.currentTemplate="blank";} if(typeof window.resetHandoffTaskForm==="function")window.resetHandoffTaskForm(); renderHandoff(); if(typeof window.renderTasks==="function")window.renderTasks();}
    window.applyHandoffTemplate=applyHandoffTemplate;
    window.openHandoffModal=openHandoffModal;
