    const SYSTEM_PROFILE_EXPORT_LABELS={systemName:"系统名称",collectiveName:"集体称呼",systemTypeText:"系统类型 / 自定义描述",description:"系统简介",frontingNotes:"前台/共前台备注",boundaries:"系统边界",comfortMethods:"安抚方式",safetyNotes:"安全提醒"};
    function getRedactionOptions(){const redacted=!!document.getElementById("exportRedacted")?.checked; const aliasMap=buildMemberAliasMap(redacted&&!!document.getElementById("exportHideMemberNames")?.checked); return {redacted,excludePrivate:redacted&&!!document.getElementById("exportExcludePrivate")?.checked,hideMemberNames:redacted&&!!document.getElementById("exportHideMemberNames")?.checked,aliasMap};}
    function shouldUseRedactedExport(){return !!document.getElementById("exportRedacted")?.checked;}
    function updateRedactionControls(){const redacted=shouldUseRedactedExport(); const exclude=document.getElementById("exportExcludePrivate"), hide=document.getElementById("exportHideMemberNames"); if(exclude)exclude.disabled=!redacted; if(hide)hide.disabled=!redacted;}
    function buildMemberAliasMap(hide=true){const map={hide,byId:new Map(),byName:new Map(),unknownCount:0}; if(!hide)return map; (data.members||[]).forEach((m,index)=>{const alias=`成员 ${index+1}`; if(m.id)map.byId.set(m.id,alias); if(m.name)map.byName.set(m.name,alias); (Array.isArray(m.aliases)?m.aliases:[]).forEach(name=>{if(name)map.byName.set(name,alias);});}); return map;}
    function redactMemberName(memberId,map,fallbackName=""){if(!map?.hide)return fallbackName||member(memberId)?.name||"已移除成员"; if(memberId&&map.byId.has(memberId))return map.byId.get(memberId); const source=String(fallbackName||"").trim(); if(source&&map.byName.has(source))return map.byName.get(source); if(source){map.unknownCount+=1; const alias=`成员 ${map.byId.size+map.unknownCount}`; map.byName.set(source,alias); return alias;} return "成员";}
    function redactTextForExport(text,options){let out=String(text||""); if(!options?.hideMemberNames)return out; const pairs=[...options.aliasMap.byName.entries()].filter(([name])=>name).sort((a,b)=>b[0].length-a[0].length); pairs.forEach(([name,alias])=>{out=out.split(name).join(alias);}); return out;}
    function redactSystemProfileForExport(profile,visibility,level="public"){const source={...blankSystemProfile(),...(profile||{})}; const visible=normalizeSystemProfileVisibilityRecord(visibility); const out={}; Object.keys(SYSTEM_PROFILE_EXPORT_LABELS).forEach(key=>{if(visible[key]===level&&String(source[key]||"").trim())out[key]=source[key];}); return out;}
    function filterRoomsForRedactedExport(rooms,options){return options?.redacted&&options.excludePrivate?rooms.filter(r=>!isPrivateRoom(r)):rooms;}
    function filterMessagesForRedactedExport(messages,options,rooms){if(!(options?.redacted&&options.excludePrivate))return messages; const ids=new Set((rooms||[]).map(r=>r.id)); return messages.filter(m=>ids.has(m.roomId));}
    function redactPollForExport(poll,options){const source=poll||{}; return {...source,comments:options?.redacted?{}:source.comments||{},decisionText:redactTextForExport(source.decisionText||"",options)};}
    function redactTaskForExport(task,options){const source=task||{}; return {...source,title:redactTextForExport(source.title||"",options),detail:redactTextForExport(source.detail||"",options)};}
    function redactedRoomName(room,options){return redactTextForExport(roomDisplayName(room)||"未知群组",options);}
    function redactedRoomDesc(room,options){return redactTextForExport(roomDisplayDesc(room)||"",options);}
    function redactedMemberNameByMessage(message,options){if(!options?.hideMemberNames)return memberNameByMessage(message); return redactMemberName(message.speakerId,options.aliasMap,memberNameByMessage(message));}
    function redactedMessageText(message,options){const text=redactTextForExport(message.text||"",options); const hasImage=!!(message.imageData||message.imageId); return `${text}${hasImage?`${text?"\n":""}[含图片]`:""}`;}
    function redactedMdMessageBody(message,options){const text=redactTextForExport(message.text||"",options).replace(/\n/g,"\n  "); const image=(message.imageData||message.imageId)?"[含图片]":""; return [text,image].filter(Boolean).join(text&&image?"\n\n  ":"");}
    function redactedSystemProfileLines(options){const profile=redactSystemProfileForExport(data.systemProfile, data.systemProfileVisibility, "public"); return Object.entries(profile).map(([key,value])=>({label:SYSTEM_PROFILE_EXPORT_LABELS[key]||key,value:redactTextForExport(value,options)}));}
    function redactedSystemProfileBlock(format,options){const lines=redactedSystemProfileLines(options); if(!lines.length)return ""; if(format==="md")return ["## 系统公开资料",...lines.map(row=>`- **${row.label}**：${row.value}`),"","可见性只影响本应用内展示和导出，不是加密隔离。"].join("\n"); return ["【系统公开资料】",...lines.map(row=>`${row.label}：${row.value}`),"可见性只影响本应用内展示和导出，不是加密隔离。"].join("\n");}
    function openExportModal(){document.getElementById("exportRoom").innerHTML=data.rooms.map(r=>`<option value="${r.id}">${esc(roomDisplayName(r))}</option>`).join(""); document.getElementById("exportRoom").value=currentRoomId; document.getElementById("exportScope").value="current"; const redacted=document.getElementById("exportRedacted"), exclude=document.getElementById("exportExcludePrivate"), hide=document.getElementById("exportHideMemberNames"); if(redacted)redacted.checked=false; if(exclude)exclude.checked=true; if(hide)hide.checked=false; updateRedactionControls(); updateExportRoomPicker(); openModal("exportModal");}
    function updateExportRoomPicker(){const isRoom=document.getElementById("exportScope").value==="room"; document.getElementById("exportRoom").style.display=isRoom?"block":"none"; document.getElementById("exportRoomLabel").style.display=isRoom?"block":"none";}
    function selectedExportRooms(){const scope=document.getElementById("exportScope").value; if(scope==="all")return data.rooms; if(scope==="room")return data.rooms.filter(r=>r.id===document.getElementById("exportRoom").value); return data.rooms.filter(r=>r.id===currentRoomId);}
    function selectedExportData(){const rooms=selectedExportRooms(); const ids=new Set(rooms.map(r=>r.id)); const messages=data.messages.filter(m=>ids.has(m.roomId)); return {rooms,messages};}
    function formatExport(format){
      const selected=selectedExportData();
      const selectedRoomIds=new Set(selected.rooms.map(r=>r.id));
      const includeLedger=document.getElementById("exportScope").value==="all";
      if(format==="json")return {text:JSON.stringify({app:"月之暗面",version:2,exportedAt:now(),nextSeq:data.nextSeq,tags:data.tags||[],messageKinds:data.messageKinds||DEFAULT_KINDS,polls:(data.polls||[]).filter(p=>selectedRoomIds.has(p.roomId)),handoffNotes:(data.handoffNotes||[]).filter(n=>selectedRoomIds.has(n.roomId)),frontingLogs:data.frontingLogs||[],...(includeLedger?{tasks:data.tasks||[],careLogs:data.careLogs||[],careChecklist:data.careChecklist||[],ledgerRecords:normalizeLedgerRecordsForBackup(getRuntimeLedgerRecordsForBackup())}:{}),systemProfile:data.systemProfile||blankSystemProfile(),systemProfileVisibility:normalizeSystemProfileVisibilityRecord(data.systemProfileVisibility),memberRelations:data.memberRelations||[],externalSystemCards:data.externalSystemCards||[],rooms:selected.rooms,members:data.members,messages:selected.messages},null,2),type:"application/json",ext:"json"};
      const options=getRedactionOptions();
      const rooms=filterRoomsForRedactedExport(selected.rooms,options);
      const messages=filterMessagesForRedactedExport(selected.messages,options,rooms);
      if(format==="csv"){
        const header=["群组","时间","校验码","校验","发言者","类型","内容"].map(csvCell).join(",");
        const profileRows=options.redacted?redactedSystemProfileLines(options).map(row=>["系统公开资料",new Date().toLocaleString(),"","", "系统档案",row.label,row.value].map(csvCell).join(",")):[];
        const rows=messages.map(m=>{const r=data.rooms.find(room=>room.id===m.roomId); return [r?redactedRoomName(r,options):"未知群组",new Date(m.createdAt).toLocaleString(),seqCode(m),integrityOk(m)?"正常":"异常",redactedMemberNameByMessage(m,options),m.kind,options.redacted?redactedMessageText(m,options):messageText(m)].map(csvCell).join(",");});
        return {text:[header,...profileRows,...rows].join("\n"),type:"text/csv;charset=utf-8",ext:"csv"};
      }
      const profileBlock=options.redacted?redactedSystemProfileBlock(format,options):"";
      const blocks=rooms.map(r=>{
        const rows=messages.filter(m=>m.roomId===r.id);
        if(format==="md"){
          return [`# ${redactedRoomName(r,options)}`,redactedRoomDesc(r,options)?`> ${redactedRoomDesc(r,options)}`:"",...rows.map(m=>`- **${new Date(m.createdAt).toLocaleString()}｜校验码 ${seqCode(m)}｜${redactedMemberNameByMessage(m,options)}｜${m.kind}**\n\n  ${options.redacted?redactedMdMessageBody(m,options):mdMessageBody(m)}`)].filter(Boolean).join("\n\n");
        }
        return [`【${redactedRoomName(r,options)}】`,redactedRoomDesc(r,options)||"",...rows.map(m=>`[${new Date(m.createdAt).toLocaleString()}] 校验码 ${seqCode(m)} · ${redactedMemberNameByMessage(m,options)} · ${m.kind}\n${options.redacted?redactedMessageText(m,options):messageText(m)}`)].filter(Boolean).join("\n\n");
      });
      return {text:[profileBlock,blocks.join("\n\n---\n\n")].filter(Boolean).join("\n\n---\n\n"),type:"text/plain;charset=utf-8",ext:format};
    }
    async function hydrateImagesForJsonExport(exportObj){let anyMissing=false; for(const m of exportObj.messages||[]){if(m.imageId&&!m.imageData){try{const blob=await window.imageStore.getImageBlob(m.imageId); if(blob){m.imageData=await window.imageStore.blobToDataUrl(blob);}else{console.warn("hydrateImagesForJsonExport: missing blob for imageId",m.imageId); anyMissing=true;}}catch(err){console.warn("hydrateImagesForJsonExport: failed to hydrate imageId",m.imageId,err); anyMissing=true;}}} for(const mb of exportObj.members||[]){if(mb.avatarId&&!mb.avatarData){try{const blob=await window.imageStore.getImageBlob(mb.avatarId); if(blob){mb.avatarData=await window.imageStore.blobToDataUrl(blob);}else{console.warn("hydrateImagesForJsonExport: missing blob for avatarId",mb.avatarId); anyMissing=true;}}catch(err){console.warn("hydrateImagesForJsonExport: failed to hydrate avatarId",mb.avatarId,err); anyMissing=true;}}} for(const r of exportObj.rooms||[]){if(r.backgroundId&&!r.backgroundData){try{const blob=await window.imageStore.getImageBlob(r.backgroundId); if(blob){r.backgroundData=await window.imageStore.blobToDataUrl(blob);}else{console.warn("hydrateImagesForJsonExport: missing blob for backgroundId",r.backgroundId); anyMissing=true;}}catch(err){console.warn("hydrateImagesForJsonExport: failed to hydrate backgroundId",r.backgroundId,err); anyMissing=true;}}} return anyMissing;}
    async function formatExportJsonAsync(){const selected=selectedExportData(); const selectedRoomIds=new Set(selected.rooms.map(r=>r.id)); const includeLedger=document.getElementById("exportScope").value==="all"; const exportObj=JSON.parse(JSON.stringify({app:"月之暗面",version:2,exportedAt:now(),nextSeq:data.nextSeq,tags:data.tags||[],messageKinds:data.messageKinds||DEFAULT_KINDS,polls:(data.polls||[]).filter(p=>selectedRoomIds.has(p.roomId)),handoffNotes:(data.handoffNotes||[]).filter(n=>selectedRoomIds.has(n.roomId)),frontingLogs:data.frontingLogs||[],...(includeLedger?{tasks:data.tasks||[],careLogs:data.careLogs||[],careChecklist:data.careChecklist||[],ledgerRecords:normalizeLedgerRecordsForBackup(getRuntimeLedgerRecordsForBackup())}:{}),systemProfile:data.systemProfile||blankSystemProfile(),systemProfileVisibility:normalizeSystemProfileVisibilityRecord(data.systemProfileVisibility),memberRelations:data.memberRelations||[],externalSystemCards:data.externalSystemCards||[],rooms:selected.rooms,members:data.members,messages:selected.messages})); const anyMissing=await hydrateImagesForJsonExport(exportObj); if(anyMissing)alert("警告：部分图片在 IndexedDB 中找不到，备份可能不完整。\n\n建议先运行 window.runImageMigrationToIndexedDB() 迁移旧图片后再导出。"); return {text:JSON.stringify(exportObj,null,2),type:"application/json",ext:"json"};}
    async function downloadExport(){const format=document.getElementById("exportFormat").value; const scope=document.getElementById("exportScope").value; const rooms=selectedExportRooms(); const options=getRedactionOptions(); if(format==="json"&&options.redacted)alert("JSON 用于完整备份，默认保留全量数据；脱敏导出请使用 Markdown / TXT / CSV。本次 JSON 会按完整备份导出。"); if(format!=="json"&&options.redacted&&options.excludePrivate&&rooms.length&&!rooms.some(r=>!isPrivateRoom(r))){alert("当前导出范围只包含私聊 / 小群聊，且已选择排除私聊，因此没有可导出的内容。可以取消“排除私聊”，或改选其它范围。"); return;} const hasPrivate=rooms.some(isPrivateRoom); if(format!=="json"&&hasPrivate&&!(options.redacted&&options.excludePrivate)){const isCurrentPrivate=scope==="current"&&rooms.length===1&&isPrivateRoom(rooms[0]); const msg=isCurrentPrivate?"当前群组是私聊 / 小群聊，是否继续导出？":"当前导出范围包含私聊 / 小群聊，是否继续？"; if(!confirm(msg))return;} let result; if(format==="json"){const btn=document.getElementById("confirmExportBtn"); btn.disabled=true; try{result=await formatExportJsonAsync();}catch(err){console.error("downloadExport: JSON export failed",err); alert("导出失败："+(err.message||err)); btn.disabled=false; return;} btn.disabled=false;} else {result=formatExport(format);} if(!result.text.trim()){alert("没有可导出的内容。"); return;} const label=scope==="all"?"全部对话":(roomDisplayName(rooms[0])||"对话"); const filename=`月之暗面-${fileSafe(options.redacted?`${label}-脱敏`:label)}-${new Date().toISOString().slice(0,10)}.${result.ext}`; if(window.MoonBridge?.saveFile){window.MoonBridge.saveFile(filename,result.type,result.text); closeModal("exportModal"); return;} const blob=new Blob([result.text],{type:result.type}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=filename; a.click(); URL.revokeObjectURL(url); closeModal("exportModal");}
    async function externalizeImagesAfterJsonImport(appData){for(const m of appData.messages||[]){if(m.imageData){const imageId=m.imageId||`msgimg-${m.id}`; const blob=window.imageStore.dataUrlToBlob(m.imageData); const mime=m.imageType||blob.type||"image/*"; await window.imageStore.putImage({id:imageId,blob,mime,name:m.imageName||"图片"}); m.imageId=imageId; delete m.imageData;}else if(m.imageId){const blob=await window.imageStore.getImageBlob(m.imageId).catch(()=>null); if(!blob)console.warn("externalizeImagesAfterJsonImport: imageId not found in IndexedDB",m.imageId);}} for(const mb of appData.members||[]){if(mb.avatarData){const avatarId=mb.avatarId||`avatar-${mb.id}`; const blob=window.imageStore.dataUrlToBlob(mb.avatarData); const mime=blob.type||"image/*"; await window.imageStore.putImage({id:avatarId,blob,mime,name:`${mb.name||"member"}-头像`}); mb.avatarId=avatarId; delete mb.avatarData;}else if(mb.avatarId){const blob=await window.imageStore.getImageBlob(mb.avatarId).catch(()=>null); if(!blob)console.warn("externalizeImagesAfterJsonImport: avatarId not found in IndexedDB",mb.avatarId);}} for(const r of appData.rooms||[]){if(r.backgroundData){const backgroundId=r.backgroundId||`roombg-${r.id}`; const blob=window.imageStore.dataUrlToBlob(r.backgroundData); const mime=blob.type||"image/*"; await window.imageStore.putImage({id:backgroundId,blob,mime,name:`${r.name||r.id||"room"}-背景`}); r.backgroundId=backgroundId; delete r.backgroundData;}else if(r.backgroundId){const blob=await window.imageStore.getImageBlob(r.backgroundId).catch(()=>null); if(!blob)console.warn("externalizeImagesAfterJsonImport: backgroundId not found in IndexedDB",r.backgroundId);}} /* JSON 导入把 DataURL 外置到 IndexedDB：imageData(_imgVer:1) → imageId(_imgVer:2)，按现有规则重算 integrity */ for(const m of appData.messages||[])m.integrity=messageIntegrity(m);}
    function importBackupFile(file){if(!file)return; const reader=new FileReader(); reader.onload=async()=>{try{const parsed=JSON.parse(String(reader.result||"")); const incoming=await storage.importBackup(parsed); const ledgerFromBackup=Array.isArray(parsed.ledgerRecords)?normalizeLedgerRecordsForBackup(parsed.ledgerRecords):null; const bad=incoming.messages.filter(m=>!integrityOk(m)).length; const note=bad?`\n\n注意：备份中有 ${bad} 条消息校验异常，仍可导入，但建议确认来源。`:""; const ledgerNote=ledgerFromBackup?`\n备份包含 ${ledgerFromBackup.length} 条账本记录，导入后会覆盖当前账本。`:"\n备份不包含账本记录，当前账本将保持不变。"; if(!confirm(`导入会覆盖当前本机数据。\n\n备份包含 ${incoming.rooms.length} 个群组、${incoming.members.length} 个成员、${incoming.messages.length} 条消息。${ledgerNote}${note}\n\n确定导入吗？`))return; await externalizeImagesAfterJsonImport(incoming); data=incoming; currentRoomId=data.rooms[0]?.id||"main"; if(!(await save()))return; let ledgerFailed=false; if(ledgerFromBackup){ledgerRecords=ledgerFromBackup; if(!(await saveLedger(ledgerFromBackup))){ledgerFailed=true; console.error("importBackupFile: ledgerRecords save failed after main data import");}} closeModal("exportModal"); if(typeof renderLedger==="function")renderLedger(); render(); alert(ledgerFailed?"备份已导入，但账本记录保存失败。当前账本可能没有完成覆盖。":"备份已导入。");}catch(err){console.error("importBackupFile failed",err); alert(err?.message==="invalid_backup"?"这不是有效的月之暗面 JSON 备份。":"导入失败：JSON 文件无法读取或图片写入存储失败。");}}; reader.onerror=()=>alert("导入失败：文件读取出错。"); reader.readAsText(file);}
