    function renderTagOptions(selected=""){const select=document.getElementById("memberTag"); select.innerHTML=`<option value="">无标签</option>${(data.tags||[]).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}`; select.value=selected&&tag(selected)?selected:"";}
    function syncTagEditor(){const t=tag(document.getElementById("memberTag").value); document.getElementById("memberTagName").value=t?.name||""; document.getElementById("memberTagColor").value=t?.color||"#8b5cf6";}
    async function saveTagFromEditor(){const name=document.getElementById("memberTagName").value.trim(); const color=document.getElementById("memberTagColor").value||"#8b5cf6"; if(!name){alert("请先填写标签名称。");return;} const selected=document.getElementById("memberTag").value; let t=tag(selected); if(t){t.name=name; t.color=color;} else {t={id:makeId(),name,color}; data.tags.push(t);} renderTagOptions(t.id); syncTagEditor(); if(await save())render();}
    async function deleteSelectedTag(){const tagId=document.getElementById("memberTag").value; const t=tag(tagId); if(!t){alert("请先选择要删除的标签。");return;} const used=data.members.filter(m=>m.tagId===tagId).length; const note=used?`\n\n当前有 ${used} 个成员正在使用这个标签，删除后会自动改为“无标签”。`:""; if(!confirm(`确定删除标签「${t.name}」吗？${note}`))return; data.tags=data.tags.filter(x=>x.id!==tagId); data.members=data.members.map(m=>m.tagId===tagId?{...m,tagId:""}:m); renderTagOptions(""); syncTagEditor(); if(await save())render();}
    function statusText(status){return {active:"活跃 / 常在",resting:"休眠 / 很少出现",gone:"消失 / 暂不可联系",unknown:"不确定"}[status]||"不确定";} function statusClass(status){if(status==="resting")return"status-rest"; if(status==="gone"||status==="unknown")return"status-gone"; return"";}
    function relationMemberName(id){return member(id)?.name||"已移除成员";}
    function renderRelationMemberOptions(){const opts=data.members.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join(""); const from=document.getElementById("relationFrom"), to=document.getElementById("relationTo"); if(from)from.innerHTML=opts; if(to)to.innerHTML=opts;}
    function resetRelationForm(){document.getElementById("relationId").value=""; renderRelationMemberOptions(); document.getElementById("relationType").value="保护"; document.getElementById("relationNote").value=""; const from=document.getElementById("relationFrom"), to=document.getElementById("relationTo"); if(data.members[0])from.value=data.members[0].id; if(data.members[1])to.value=data.members[1].id;}
    function renderRelations(){const box=document.getElementById("relationList"); if(!box)return; renderRelationMemberOptions(); const rows=data.memberRelations||[]; box.innerHTML=rows.length?rows.map(r=>`<div class="relation-card"><div class="relation-title">${esc(relationMemberName(r.fromMemberId))} → ${esc(relationMemberName(r.toMemberId))}</div><div class="relation-type">关系：${esc(r.relationType||"不确定")}</div>${r.note?`<p>${esc(r.note)}</p>`:""}<div class="row"><button class="light small" type="button" onclick="editRelation('${esc(r.id)}')">编辑</button><button class="danger small" type="button" onclick="deleteRelation('${esc(r.id)}')">删除</button></div></div>`).join(""):'<div class="empty">还没有成员关系。</div>';}
    async function saveRelation(){const id=document.getElementById("relationId").value; const fromMemberId=document.getElementById("relationFrom").value; const toMemberId=document.getElementById("relationTo").value; const relationType=document.getElementById("relationType").value.trim()||"不确定"; const note=document.getElementById("relationNote").value.trim(); if(!fromMemberId||!toMemberId){alert("请先选择两个成员。");return;} if(fromMemberId===toMemberId){alert("成员 A 和成员 B 不能相同。");return;} const duplicate=(data.memberRelations||[]).find(r=>r.id!==id&&r.fromMemberId===fromMemberId&&r.toMemberId===toMemberId&&r.relationType===relationType); if(duplicate&&!confirm("这两个成员已经有相同类型的关系，仍然继续保存吗？"))return; if(id){const r=data.memberRelations.find(x=>x.id===id); if(!r)return; Object.assign(r,{fromMemberId,toMemberId,relationType,note,updatedAt:now()});} else {data.memberRelations=data.memberRelations||[]; data.memberRelations.push({id:makeId(),fromMemberId,toMemberId,relationType,note,createdAt:now(),updatedAt:now()});} if(await save()){resetRelationForm(); renderRelations(); renderStructureView();}}
    window.editRelation=function(id){const r=(data.memberRelations||[]).find(x=>x.id===id); if(!r)return; renderRelationMemberOptions(); document.getElementById("relationId").value=r.id; document.getElementById("relationFrom").value=r.fromMemberId; document.getElementById("relationTo").value=r.toMemberId; document.getElementById("relationType").value=r.relationType||"不确定"; document.getElementById("relationNote").value=r.note||"";};
    window.deleteRelation=async function(id){const r=(data.memberRelations||[]).find(x=>x.id===id); if(!r)return; if(!confirm(`确定删除关系「${relationMemberName(r.fromMemberId)} → ${relationMemberName(r.toMemberId)}：${r.relationType}」吗？`))return; data.memberRelations=(data.memberRelations||[]).filter(x=>x.id!==id); if(await save()){renderRelations(); renderStructureView();}};
    async function renderStructureView(){try{const groupBox=document.getElementById("structureGroups"), relBox=document.getElementById("structureRelations"), detail=document.getElementById("structureMemberDetail"); if(!groupBox||!relBox)return; if(detail&&!detail.dataset.memberId)detail.innerHTML='<div class="empty">点击成员卡片可在这里查看简单描述。</div>'; const avatarUrlMap=await buildStoredImageUrlMap(data.members,"avatarId","avatarData"); const tagIds=["",...(data.tags||[]).map(t=>t.id)]; groupBox.innerHTML=tagIds.map(tagId=>{const t=tag(tagId); const members=data.members.filter(m=>(m.tagId||"")===tagId); if(!members.length)return ""; return `<div class="system-group"><h3>${tagDot(tagId)}${esc(t?.name||"无标签")}</h3><div class="system-members">${members.map(m=>`<div class="system-member-card" onclick="showStructureMember('${esc(m.id)}')">${tagDot(m.tagId)}<div class="avatar">${avatarContent(m.name,avatarUrlMap.get(m.id)||"")}</div><div class="meta"><strong>${esc(m.name)}</strong><span>${esc(statusText(m.status))} · ${esc(m.role||"未填写角色")}</span></div></div>`).join("")}</div></div>`;}).filter(Boolean).join("")||'<div class="empty">还没有成员。</div>'; const grouped={}; (data.memberRelations||[]).forEach(r=>{const key=r.relationType||"不确定"; (grouped[key]||(grouped[key]=[])).push(r);}); relBox.innerHTML=Object.keys(grouped).length?Object.entries(grouped).map(([type,rows])=>`<div class="system-card"><strong>${esc(type)}</strong>${rows.map(r=>`<p onclick="editRelation('${esc(r.id)}')">${esc(relationMemberName(r.fromMemberId))} → ${esc(relationMemberName(r.toMemberId))}：${esc(r.relationType||"不确定")}</p>`).join("")}</div>`).join(""):'<div class="empty">还没有成员关系。</div>';}catch(err){console.error("renderStructureView failed",err);}}
    window.showStructureMember=async function(memberId){try{const m=member(memberId); const detail=document.getElementById("structureMemberDetail"); if(!m||!detail)return; const avatarUrl=await resolveStoredImageUrl(m,"avatarId","avatarData"); detail.dataset.memberId=memberId; detail.innerHTML=`<div class="system-member-summary"><div class="avatar">${avatarContent(m.name,avatarUrl)}</div><div class="meta"><strong>${esc(m.name)}</strong><span>${esc(statusText(m.status))} · ${esc(tagName(m.tagId))} · ${esc(m.role||"未填写角色")}</span><p>${esc(m.note||"暂无成员备注。")}</p></div></div>`;}catch(err){console.error("showStructureMember failed",err);}};
    function openSystemModal(){renderSystemProfile(); resetRelationForm(); renderRelations(); renderStructureView(); renderSystemCardPanel(); document.querySelectorAll("#systemModal .settings-tabs button").forEach((btn,i)=>btn.classList.toggle("active",i===0)); document.querySelectorAll("#systemModal .settings-panel").forEach((panel,i)=>panel.classList.toggle("active",i===0)); openModal("systemModal");}
    function resetMemberModal(){document.getElementById("memberModalTitle").textContent="添加系统成员"; document.getElementById("memberId").value=""; document.getElementById("memberName").value=""; document.getElementById("memberStatus").value="active"; renderTagOptions(""); syncTagEditor(); document.getElementById("memberRole").value=""; document.getElementById("memberNote").value=""; pendingMemberAvatar=null; setPreview("memberAvatarPreview",null,"头像");}
