    function setPreview(id,src,label){document.getElementById(id).innerHTML=src?`<img src="${esc(src)}" alt="${esc(label)}" />`:label;}
    function looksLikeImage(file){return file?.type?.startsWith("image/")||/\.(png|jpe?g|gif|webp|bmp|svg|heic|heif)$/i.test(file?.name||"");}
    function readImageFile(file,maxMb,done,opts={}){if(!file)return; if(!looksLikeImage(file)){alert("请选择图片文件。");return;} const maxBytes=maxMb*1024*1024; const reader=new FileReader(); reader.onerror=()=>alert("图片读取失败，请换一张图片试试。"); reader.onload=()=>{const raw=String(reader.result||""); const name=file.name||""; if(!opts.compress||/\.(svg|gif)$/i.test(name)){if(file.size>maxBytes){alert(`图片太大了，请选择 ${maxMb}MB 以内的图片。`);return;} done(raw); return;} const img=new Image(); img.onload=()=>{try{const maxSide=opts.maxSide||640; const scale=Math.min(1,maxSide/Math.max(img.width,img.height)); const canvas=document.createElement("canvas"); canvas.width=Math.max(1,Math.round(img.width*scale)); canvas.height=Math.max(1,Math.round(img.height*scale)); const ctx=canvas.getContext("2d"); ctx.drawImage(img,0,0,canvas.width,canvas.height); let out; try{out=canvas.toDataURL("image/webp",opts.quality||0.84);}catch{out=canvas.toDataURL("image/jpeg",opts.quality||0.84);} done(out.length<raw.length||file.size>maxBytes?out:raw);}catch{if(file.size>maxBytes){alert("图片处理失败，请换一张更小的图片。");return;} done(raw);}}; img.onerror=()=>{if(file.size>maxBytes){alert("图片读取失败，请换一张更小的图片。");return;} done(raw);}; img.src=raw;}; reader.readAsDataURL(file);}
    function readImageForCrop(file,done){if(!file)return; if(!looksLikeImage(file)){alert("请选择图片文件。");return;} const reader=new FileReader(); reader.onerror=()=>alert("图片读取失败，请换一张图片试试。"); reader.onload=()=>done(String(reader.result||"")); reader.readAsDataURL(file);}
    const cropper={img:null,opts:null,baseScale:1,zoom:1,offsetX:0,offsetY:0,dragging:false,lastX:0,lastY:0,mode:"cover"};
    function cropCanvas(){return document.getElementById("cropCanvas");}
    function clampCropOffset(){const c=cropCanvas(); if(!cropper.img)return; const scale=cropper.baseScale*cropper.zoom; const w=cropper.img.width*scale, h=cropper.img.height*scale; cropper.offsetX=w<=c.width?(c.width-w)/2:Math.min(0,Math.max(c.width-w,cropper.offsetX)); cropper.offsetY=h<=c.height?(c.height-h)/2:Math.min(0,Math.max(c.height-h,cropper.offsetY));}
    function drawCropper(){const c=cropCanvas(); const ctx=c.getContext("2d"); ctx.clearRect(0,0,c.width,c.height); ctx.fillStyle="#111827"; ctx.fillRect(0,0,c.width,c.height); if(!cropper.img)return; clampCropOffset(); const scale=cropper.baseScale*cropper.zoom; ctx.drawImage(cropper.img,cropper.offsetX,cropper.offsetY,cropper.img.width*scale,cropper.img.height*scale);}
    function cropScaleForMode(c){return cropper.mode==="contain"?Math.min(c.width/cropper.img.width,c.height/cropper.img.height):Math.max(c.width/cropper.img.width,c.height/cropper.img.height);}
    function resetCropperView(){const c=cropCanvas(); const aspect=Math.max(.25,Math.min(4,cropper.opts.aspectRatio||1)); const maxW=720,maxH=520; let w=maxW,h=Math.round(w/aspect); if(h>maxH){h=maxH; w=Math.round(h*aspect);} c.width=Math.max(240,w); c.height=Math.max(180,h); cropper.mode=document.getElementById("cropMode").value||cropper.opts.mode||"cover"; cropper.baseScale=cropScaleForMode(c); cropper.zoom=1; cropper.offsetX=(c.width-cropper.img.width*cropper.baseScale)/2; cropper.offsetY=(c.height-cropper.img.height*cropper.baseScale)/2; document.getElementById("cropZoom").value="1"; drawCropper();}
    function openCropper(opts){const img=new Image(); img.onload=()=>{cropper.img=img; cropper.opts=opts; cropper.mode=opts.mode||"cover"; document.getElementById("cropTitle").textContent=opts.title||"图片裁剪"; document.getElementById("cropMode").value=cropper.mode; document.getElementById("cropModeLabel").style.display=opts.allowModeSwitch===false?"none":"block"; openModal("cropModal"); resetCropperView();}; img.onerror=()=>alert("图片加载失败，无法裁剪。"); img.src=opts.src;}
    function confirmCropper(){if(!cropper.img||!cropper.opts)return; try{const out=document.createElement("canvas"); out.width=cropper.opts.outputWidth; out.height=cropper.opts.outputHeight; const ctx=out.getContext("2d"); ctx.fillStyle=cropper.opts.fillColor||"#f7f8fa"; ctx.fillRect(0,0,out.width,out.height); const ratio=out.width/cropCanvas().width; const scale=cropper.baseScale*cropper.zoom*ratio; ctx.drawImage(cropper.img,cropper.offsetX*ratio,cropper.offsetY*ratio,cropper.img.width*scale,cropper.img.height*scale); let dataUrl; try{dataUrl=out.toDataURL("image/webp",cropper.opts.quality); if(!dataUrl.startsWith("data:image/webp"))dataUrl=out.toDataURL("image/jpeg",cropper.opts.quality);}catch{dataUrl=out.toDataURL("image/jpeg",cropper.opts.quality);} closeModal("cropModal"); const done=cropper.opts.onDone; cropper.img=null; cropper.opts=null; done&&done(dataUrl);}catch(err){alert("裁剪失败，请换一张图片试试。");}}
    function cropPointerPos(e){const p=e.touches?.[0]||e; return {x:p.clientX,y:p.clientY};}
    function beginCropDrag(e){if(!cropper.img)return; e.preventDefault(); const p=cropPointerPos(e); cropper.dragging=true; cropper.lastX=p.x; cropper.lastY=p.y;}
    function moveCropDrag(e){if(!cropper.dragging)return; e.preventDefault(); const p=cropPointerPos(e); cropper.offsetX+=p.x-cropper.lastX; cropper.offsetY+=p.y-cropper.lastY; cropper.lastX=p.x; cropper.lastY=p.y; drawCropper();}
    function endCropDrag(){cropper.dragging=false;}
    function refreshPendingImagePreview(){if(!pendingChatImage)return; const send=document.getElementById("sendImagePreview"); const edit=document.getElementById("editImagePreview"); if(send)send.src=pendingChatImage.dataUrl; if(edit)edit.src=pendingChatImage.dataUrl;}
    async function sendChatImage(dataUrl){const sp=member(speaker.value); if(!sp){alert("请先选择一个可用成员作为发言身份。");return;} const msgId=makeId(); const imageId=`msgimg-${msgId}`; const imageName=pendingChatImage?.name||"图片"; const imageType=pendingChatImage?.type||"image/*"; try{const blob=window.imageStore.dataUrlToBlob(dataUrl); const mime=blob.type||imageType; await window.imageStore.putImage({id:imageId,blob,mime,name:imageName});}catch(err){console.error("sendChatImage: failed to save image to IndexedDB",err); alert("图片保存失败，请重试。"); return;} data.messages.push(makeMessage({id:msgId,roomId:currentRoomId,speakerId:sp.id,speakerName:sp.name,kind:"图片",text:document.getElementById("message").value.trim(),imageId,imageName,imageType})); if(!(await save()))return; document.getElementById("message").value=""; pendingChatImage=null; closeModal("sendImageModal"); render();}
    function openSendImagePreview(file){const sp=member(speaker.value); if(!sp){alert("请先选择一个可用成员作为发言身份。");return;} readImageFile(file,6,dataUrl=>{pendingChatImage={dataUrl,name:file.name,type:file.type||"image/*"}; refreshPendingImagePreview(); openModal("sendImageModal");},{compress:true,maxSide:960,quality:.86});}
    function openImageEditor(){if(!pendingChatImage)return; refreshPendingImagePreview(); openModal("imageEditModal");}
    function rotatePendingChatImage(){if(!pendingChatImage)return; const img=new Image(); img.onload=()=>{try{const canvas=document.createElement("canvas"); canvas.width=img.height; canvas.height=img.width; const ctx=canvas.getContext("2d"); ctx.translate(canvas.width/2,canvas.height/2); ctx.rotate(Math.PI/2); ctx.drawImage(img,-img.width/2,-img.height/2); let out; try{out=canvas.toDataURL("image/webp",.86); if(!out.startsWith("data:image/webp"))out=canvas.toDataURL("image/jpeg",.86);}catch{out=canvas.toDataURL("image/jpeg",.86);} pendingChatImage.dataUrl=out; pendingChatImage.type=out.startsWith("data:image/webp")?"image/webp":"image/jpeg"; refreshPendingImagePreview();}catch{alert("旋转失败，请换一张图片试试。");}}; img.onerror=()=>alert("图片加载失败，无法旋转。"); img.src=pendingChatImage.dataUrl;}
    function cropPendingChatImage(){if(!pendingChatImage)return; const img=new Image(); img.onload=()=>{const maxW=Math.min(960,img.width); const outW=Math.max(1,Math.round(maxW)); const outH=Math.max(1,Math.round(outW*(img.height/img.width))); openCropper({src:pendingChatImage.dataUrl,aspectRatio:img.width/img.height,outputWidth:outW,outputHeight:outH,quality:.86,title:"裁剪发送图片",mode:"contain",fillColor:"#f7f8fa",onDone:dataUrl=>{pendingChatImage.dataUrl=dataUrl; pendingChatImage.type=dataUrl.startsWith("data:image/webp")?"image/webp":"image/jpeg"; refreshPendingImagePreview();}});}; img.onerror=()=>alert("图片加载失败，无法裁剪。"); img.src=pendingChatImage.dataUrl;}
    const annotator={img:null,tool:"pen",actions:[],current:null,drawing:false};
    function annotateCanvas(){return document.getElementById("annotateCanvas");}
    function setAnnotateTool(tool){annotator.tool=tool; ["Pen","Text","Arrow"].forEach(name=>document.getElementById(`annotate${name}Btn`).classList.toggle("active",tool===name.toLowerCase()));}
    function annotateColor(){return document.getElementById("annotateColor").value||"#ef4444";}
    function annotateSize(){return Math.max(2,Number(document.getElementById("annotateSize").value)||4);}
    function annotatePoint(e){const c=annotateCanvas(), r=c.getBoundingClientRect(); return {x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
    function drawArrow(ctx,a){const dx=a.x2-a.x1, dy=a.y2-a.y1, angle=Math.atan2(dy,dx), head=Math.max(12,a.size*4); ctx.beginPath(); ctx.moveTo(a.x1,a.y1); ctx.lineTo(a.x2,a.y2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(a.x2,a.y2); ctx.lineTo(a.x2-head*Math.cos(angle-Math.PI/6),a.y2-head*Math.sin(angle-Math.PI/6)); ctx.lineTo(a.x2-head*Math.cos(angle+Math.PI/6),a.y2-head*Math.sin(angle+Math.PI/6)); ctx.closePath(); ctx.fill();}
    function drawAnnotateAction(ctx,a){ctx.save(); ctx.strokeStyle=a.color; ctx.fillStyle=a.color; ctx.lineWidth=a.size; ctx.lineCap="round"; ctx.lineJoin="round"; if(a.type==="pen"){ctx.beginPath(); a.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)); ctx.stroke();} else if(a.type==="arrow"){drawArrow(ctx,a);} else if(a.type==="text"){const fontSize=Math.max(16,a.size*5); ctx.font=`700 ${fontSize}px system-ui, -apple-system, BlinkMacSystemFont, sans-serif`; ctx.textBaseline="top"; ctx.lineWidth=Math.max(3,a.size/1.5); ctx.strokeStyle="rgba(255,255,255,.82)"; ctx.strokeText(a.text,a.x,a.y); ctx.fillStyle=a.color; ctx.fillText(a.text,a.x,a.y);} ctx.restore();}
    function redrawAnnotator(extra=null){const c=annotateCanvas(), ctx=c.getContext("2d"); ctx.clearRect(0,0,c.width,c.height); ctx.fillStyle="#f7f8fa"; ctx.fillRect(0,0,c.width,c.height); if(annotator.img)ctx.drawImage(annotator.img,0,0,c.width,c.height); annotator.actions.forEach(a=>drawAnnotateAction(ctx,a)); if(annotator.current)drawAnnotateAction(ctx,annotator.current); if(extra)drawAnnotateAction(ctx,extra);}
    function openAnnotator(){if(!pendingChatImage)return; const img=new Image(); img.onload=()=>{const c=annotateCanvas(); const maxSide=1600, scale=Math.min(1,maxSide/Math.max(img.width,img.height)); c.width=Math.max(1,Math.round(img.width*scale)); c.height=Math.max(1,Math.round(img.height*scale)); annotator.img=img; annotator.actions=[]; annotator.current=null; annotator.drawing=false; setAnnotateTool("pen"); redrawAnnotator(); openModal("annotateModal");}; img.onerror=()=>alert("图片加载失败，无法标注。"); img.src=pendingChatImage.dataUrl;}
    function beginAnnotate(e){if(!annotator.img)return; e.preventDefault(); annotateCanvas().setPointerCapture?.(e.pointerId); const p=annotatePoint(e); const color=annotateColor(), size=annotateSize(); if(annotator.tool==="text"){const text=document.getElementById("annotateTextInput").value.trim(); if(!text){alert("请先输入要添加的文字。");return;} annotator.actions.push({type:"text",x:p.x,y:p.y,text,color,size}); redrawAnnotator(); return;} annotator.drawing=true; annotator.current=annotator.tool==="arrow"?{type:"arrow",x1:p.x,y1:p.y,x2:p.x,y2:p.y,color,size}:{type:"pen",points:[p],color,size}; redrawAnnotator();}
    function moveAnnotate(e){if(!annotator.drawing||!annotator.current)return; e.preventDefault(); const p=annotatePoint(e); if(annotator.current.type==="pen")annotator.current.points.push(p); else {annotator.current.x2=p.x; annotator.current.y2=p.y;} redrawAnnotator();}
    function endAnnotate(){if(!annotator.drawing||!annotator.current)return; annotator.drawing=false; if(annotator.current.type!=="arrow"||Math.hypot(annotator.current.x2-annotator.current.x1,annotator.current.y2-annotator.current.y1)>4)annotator.actions.push(annotator.current); annotator.current=null; redrawAnnotator();}
    function undoAnnotate(){annotator.actions.pop(); redrawAnnotator();}
    function clearAnnotate(){if(!annotator.actions.length)return; if(confirm("确定清空这张图片上的所有标注吗？")){annotator.actions=[]; annotator.current=null; redrawAnnotator();}}
    function confirmAnnotate(){if(!pendingChatImage)return; try{const c=annotateCanvas(); let out; try{out=c.toDataURL("image/webp",.86); if(!out.startsWith("data:image/webp"))out=c.toDataURL("image/jpeg",.86);}catch{out=c.toDataURL("image/jpeg",.86);} pendingChatImage.dataUrl=out; pendingChatImage.type=out.startsWith("data:image/webp")?"image/webp":"image/jpeg"; pendingChatImage.name=(pendingChatImage.name||"图片").replace(/(\.[^.]+)?$/,"-标注$1"); refreshPendingImagePreview(); closeModal("annotateModal");}catch{alert("保存标注失败，请换一张图片试试。");}}
    function addSystemMessage(text){data.messages.push(makeMessage({roomId:currentRoomId,speakerId:"system",speakerName:"系统通知",kind:"成员变动",text}));}
