    function pollDeadlineText(value){return value?new Date(value).toLocaleString():"未设置";}
    function pollResultText(p){const counts={}; (p.options||[]).forEach(o=>counts[o.id]=0); Object.values(p.votes||{}).forEach(v=>{if(counts[v]!=null)counts[v]+=1;}); const total=Object.keys(p.votes||{}).length; const lines=(p.options||[]).map(o=>`${o.text}：${counts[o.id]||0} 票`).join("\n"); const winner=(p.options||[]).slice().sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0))[0]; return `系统投票结果\n主题：${p.title}\n截止：${pollDeadlineText(p.deadline)}\n参与：${total} 票\n${lines}\n结果：${winner?winner.text:"无"}`;}
    function closePoll(p,manual=false){if(!p||p.status==="closed")return; p.status="closed"; p.closedAt=now(); const text=pollResultText(p)+(manual?"\n结算方式：手动结束":"\n结算方式：到期自动结算"); data.messages.push(makeMessage({roomId:p.roomId||currentRoomId,speakerId:"system",speakerName:"系统通知",kind:"系统投票",text})); appendHandoff(text,"系统投票",p.roomId||currentRoomId);}
    async function closeDuePolls(){let changed=false; const t=Date.now(); (data.polls||[]).forEach(p=>{if(p.status==="open"&&p.deadline&&new Date(p.deadline).getTime()<=t){closePoll(p,false); changed=true;}}); if(changed)await save(); return changed;}
    async function createPoll(){const title=document.getElementById("pollTitle").value.trim(); const optionLines=document.getElementById("pollOptions").value.split(/\n+/).map(x=>x.trim()).filter(Boolean); const deadline=document.getElementById("pollDeadline").value; if(!title){alert("请先填写投票内容。");return;} if(optionLines.length<2){alert("请至少填写两个选项。");return;} if(!deadline){alert("请设置投票截止时间。");return;} if(new Date(deadline).getTime()<=Date.now()){alert("截止时间需要晚于现在。");return;} const poll={id:makeId(),roomId:currentRoomId,title,options:optionLines.map(text=>({id:makeId(),text})),deadline,createdAt:now(),status:"open",votes:{}}; data.polls=data.polls||[]; data.polls.push(poll); data.messages.push(makeMessage({roomId:currentRoomId,speakerId:"system",speakerName:"系统通知",kind:"系统投票",text:`系统投票已发起\n主题：${title}\n截止：${pollDeadlineText(deadline)}\n选项：\n${optionLines.map((x,i)=>`${i+1}. ${x}`).join("\n")}`})); if(!(await save()))return; document.getElementById("pollTitle").value=""; document.getElementById("pollOptions").value=""; render();}
    async function votePoll(pollId,optionId){const p=(data.polls||[]).find(x=>x.id===pollId); const sp=member(speaker.value); if(!p||p.status!=="open"||!sp)return; p.votes=p.votes||{}; p.votes[sp.id]=optionId; if(await save())renderPolls();}
    function renderPolls(){const box=document.getElementById("pollList"); if(!box)return; const roomPolls=(data.polls||[]).filter(p=>p.roomId===currentRoomId).slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); const activeSpeaker=speaker.value; box.innerHTML=roomPolls.length?roomPolls.map(p=>{const voted=p.votes?.[activeSpeaker]||""; const counts={}; p.options.forEach(o=>counts[o.id]=0); Object.values(p.votes||{}).forEach(v=>{if(counts[v]!=null)counts[v]+=1;}); const actions=p.status==="open"?`<button class="danger small" type="button" onclick="finishPoll('${esc(p.id)}')">结束并写入</button>`:`<button class="light small" type="button" onclick="copyPollResult('${esc(p.id)}')">再写入交接</button>`; return `<div class="poll-card"><strong>${esc(p.title)}</strong><div class="poll-meta">${p.status==="open"?"进行中":"已结束"} · 截止 ${esc(pollDeadlineText(p.deadline))} · ${Object.keys(p.votes||{}).length} 票</div><div class="poll-options">${p.options.map(o=>`<label><input type="radio" name="poll-${esc(p.id)}" ${voted===o.id?"checked":""} ${p.status==="open"?"":"disabled"} onchange="votePoll('${esc(p.id)}','${esc(o.id)}')" />${esc(o.text)}（${counts[o.id]||0}）</label>`).join("")}</div><div class="row">${actions}<button class="danger small" type="button" onclick="deletePoll('${esc(p.id)}')">删除投票</button></div></div>`;}).join(""):'<div class="empty">当前群组还没有投票。</div>';}
    window.votePoll=votePoll;
    window.finishPoll=async function(id){const p=(data.polls||[]).find(x=>x.id===id); if(!p)return; if(!confirm("确定结束这个投票，并把结果写入聊天和交接便签吗？"))return; closePoll(p,true); if(await save())render();};
    window.deletePoll=async function(id){const p=(data.polls||[]).find(x=>x.id===id); if(!p)return; const note=p.status==="open"?"\n\n这个投票还在进行中，删除后不会再结算。":"\n\n已经写入聊天或交接便签的结果不会被删除。"; if(!confirm(`确定删除投票「${p.title}」吗？${note}`))return; data.polls=(data.polls||[]).filter(x=>x.id!==id); if(await save())renderPolls();};
    window.copyPollResult=async function(id){const p=(data.polls||[]).find(x=>x.id===id); if(!p)return; appendHandoff(pollResultText(p),"系统投票",p.roomId||currentRoomId); if(await save()){renderHandoff(); alert("已追加到交接便签。");}};
