    function isPrivateRoom(r){return r?.type==="private";}
    function privateKey(ids){return [...(ids||[])].sort().join("|");}
    function privateNoun(r){return (r?.memberIds||[]).length>2?"小群聊":term("privateRoom");}
    function roomDisplayName(r){if(!isPrivateRoom(r))return r?.name||`未命名${term("room")}`; if(r.name)return r.name; const names=(r.memberIds||[]).map(id=>member(id)?.name||`已移除${term("member")}`); if(names.length===2)return names.join(" ↔ "); if(names.length>2)return `${names.slice(0,2).join("、")} 等 ${names.length} 人`; return term("privateRoom");}
    function roomDisplayDesc(r){if(!isPrivateRoom(r))return r?.desc||""; const names=(r.memberIds||[]).map(id=>member(id)?.name||`已移除${term("member")}`); return `${privateNoun(r)} · ${names.join(" / ")}`;}
    function setRoomModalText(kind){const isPrivate=kind==="private"; const noun=isPrivate?term("privateRoom"):term("room"); document.getElementById("roomModalTitle").textContent=isPrivate?`编辑${noun}`:`新建${noun}`; document.getElementById("roomNameLabel").textContent=`${noun}名称`; document.getElementById("roomDescLabel").textContent=isPrivate?`${noun}说明`:"说明"; document.getElementById("newRoomName").placeholder=isPrivate?"例如：A 与 B":"例如：内部会议、睡前整理、危机安抚"; document.getElementById("newRoomDesc").placeholder=isPrivate?`这个${noun}主要用来记录什么`:`这个${noun}主要用来记录什么`;}
    function resetRoomModal(){setRoomModalText("group"); document.getElementById("roomId").value=""; document.getElementById("newRoomName").value=""; document.getElementById("newRoomDesc").value=""; pendingRoomBg=null; setPreview("roomBgPreview",null,"背景");}
    function maybeShowPrivateRoomNotice(){if(prefs.privateRoomNoticeSeen)return; alert(`${term("privateRoom")}和小群聊只控制本应用内的显示范围，不代表现实记忆隔离，也不是加密隐私功能。请谨慎记录高度敏感内容。`); prefs.privateRoomNoticeSeen=true; safeSavePrefs(`${term("privateRoom")}提示状态保存`);}
    function openPrivateModal(preselected=[]){const list=Array.isArray(preselected)?preselected:(preselected?[preselected]:[]); const vm=currentViewMember(); const seed=new Set(list); if(vm)seed.add(vm.id); renderPrivateMemberOptions([...seed]); document.getElementById("privateRoomName").value=""; if(typeof applyTermsToStaticLabels==="function")applyTermsToStaticLabels(); openModal("privateModal");}
    function renderPrivateMemberOptions(preselected=[]){const set=new Set(preselected||[]); const box=document.getElementById("privateMemberList"); box.innerHTML=data.members.length?data.members.map(m=>{const tail=m.status==="gone"?'<span class="hint">已消失</span>':m.status==="resting"?'<span class="hint">休眠</span>':m.status==="unknown"?'<span class="hint">不确定</span>':""; return `<label class="member-pick ${m.status==="gone"?"gone":""}"><input type="checkbox" value="${esc(m.id)}" ${set.has(m.id)?"checked":""} />${tagDot(m.tagId)}<span class="name">${esc(m.name)}</span>${tail}</label>`;}).join(""):`<div class="empty">还没有${esc(term("member"))}。先到${esc(term("member"))}栏添加。</div>`;}
    async function createPrivateRoom(){const checked=[...document.querySelectorAll("#privateMemberList input:checked")].map(c=>c.value); if(checked.length<2){alert(`请至少选择 2 个${term("member")}。`);return;} const key=privateKey(checked); let r=data.rooms.find(x=>x.type==="private"&&privateKey(x.memberIds||[])===key); if(!r){r={id:makeId(),type:"private",memberIds:checked,name:document.getElementById("privateRoomName").value.trim(),desc:"",createdAt:now()}; data.rooms.push(r);} if(!prefs.showAllPrivateRooms&&!prefs.currentViewMemberId){prefs.currentViewMemberId=checked[0]; await savePrefs();} currentRoomId=r.id; if(!(await save()))return; closeModal("privateModal"); setTab("private"); maybeShowPrivateRoomNotice(); render();}
    async function openPrivateWith(targetId){const vm=currentViewMember(); if(vm){if(vm.id===targetId){alert(`不能和自己创建${term("privateRoom")}。`);return;} const ids=[vm.id,targetId]; const key=privateKey(ids); let r=data.rooms.find(x=>x.type==="private"&&privateKey(x.memberIds||[])===key); if(!r){r={id:makeId(),type:"private",memberIds:ids,name:"",desc:"",createdAt:now()}; data.rooms.push(r);} currentRoomId=r.id; if(!(await save()))return; setTab("private"); maybeShowPrivateRoomNotice(); render();} else {openPrivateModal([targetId]);}}
