    const SYSTEM_PROFILE_FIELD_INPUTS={profileSystemName:"systemName",profileCollectiveName:"collectiveName",profileSystemTypeText:"systemTypeText",profileDescription:"description",profileFrontingNotes:"frontingNotes",profileBoundaries:"boundaries",profileComfortMethods:"comfortMethods",profileSafetyNotes:"safetyNotes"};
    const SYSTEM_PROFILE_VISIBILITY_INPUTS={systemName:"profileSystemNameVisibility",collectiveName:"profileCollectiveNameVisibility",systemTypeText:"profileSystemTypeTextVisibility",description:"profileDescriptionVisibility",frontingNotes:"profileFrontingNotesVisibility",boundaries:"profileBoundariesVisibility",comfortMethods:"profileComfortMethodsVisibility",safetyNotes:"profileSafetyNotesVisibility"};
    const SYSTEM_CARD_PROFILE_FIELDS=[{key:"systemName",id:"cardFieldSystemName"},{key:"collectiveName",id:"cardFieldCollectiveName"},{key:"systemTypeText",id:"cardFieldSystemTypeText"},{key:"description",id:"cardFieldDescription"},{key:"boundaries",id:"cardFieldBoundaries"},{key:"comfortMethods",id:"cardFieldComfortMethods"},{key:"safetyNotes",id:"cardFieldSafetyNotes",alwaysConfirm:true}];
    function currentSystemProfileVisibility(){return normalizeSystemProfileVisibilityRecord(data.systemProfileVisibility);}
    function renderSystemProfile(){const p={...blankSystemProfile(),...(data.systemProfile||{})}; const visibility=currentSystemProfileVisibility(); Object.entries(SYSTEM_PROFILE_FIELD_INPUTS).forEach(([id,key])=>{const el=document.getElementById(id); if(el&&el.value!==p[key])el.value=p[key]||"";}); Object.entries(SYSTEM_PROFILE_VISIBILITY_INPUTS).forEach(([key,id])=>{const el=document.getElementById(id); if(el)el.value=normalizeSystemProfileVisibilityValue(key,visibility[key]);});}
    function collectSystemProfileVisibility(){const current=currentSystemProfileVisibility(); const out={}; Object.entries(SYSTEM_PROFILE_VISIBILITY_INPUTS).forEach(([key,id])=>{out[key]=normalizeSystemProfileVisibilityValue(key,document.getElementById(id)?.value||current[key]);}); return normalizeSystemProfileVisibilityRecord(out);}
    async function saveSystemProfile(){data.systemProfile={...blankSystemProfile(),...(data.systemProfile||{}),systemName:document.getElementById("profileSystemName").value.trim(),collectiveName:document.getElementById("profileCollectiveName").value.trim(),systemTypeText:document.getElementById("profileSystemTypeText").value.trim(),description:document.getElementById("profileDescription").value.trim(),frontingNotes:document.getElementById("profileFrontingNotes").value.trim(),boundaries:document.getElementById("profileBoundaries").value.trim(),comfortMethods:document.getElementById("profileComfortMethods").value.trim(),safetyNotes:document.getElementById("profileSafetyNotes").value.trim(),updatedAt:now()}; data.systemProfileVisibility=collectSystemProfileVisibility(); pendingSystemCardPayload=null; pendingSystemCardImage=null; if(await save()){await render(); alert("系统简介已保存。");}}
    function systemCardPublicCustomFields(m){return normalizeMemberCustomFields(m?.customFields||[]).filter(f=>f.visibility==="public"&&String(f.value||"").trim()).map(f=>({name:String(f.name||"").slice(0,60),value:String(f.value||"").slice(0,180)}));}
    function normalizeSystemCard(card={}){return {type:"moon-system-card",schemaVersion:1,createdAt:card.createdAt||now(),systemName:String(card.systemName||""),collectiveName:String(card.collectiveName||""),systemTypeText:String(card.systemTypeText||""),description:String(card.description||""),boundaries:String(card.boundaries||""),comfortMethods:String(card.comfortMethods||""),safetyNotes:String(card.safetyNotes||""),publicMembers:Array.isArray(card.publicMembers)?card.publicMembers.map(m=>({name:String(m.name||"").slice(0,60),role:String(m.role||"").slice(0,80),customFields:Array.isArray(m.customFields)?m.customFields.map(f=>({name:String(f.name||"").slice(0,60),value:String(f.value||"").slice(0,180)})).filter(f=>f.name&&f.value):[]})).filter(m=>m.name||m.role||m.customFields.length):[]};}
    function shortText(v,n=90){const s=String(v||"").replace(/\s+/g," ").trim(); return s.length>n?s.slice(0,n-1)+"…":s;}
    function syncSystemCardFieldDefaults(){const visibility=currentSystemProfileVisibility(); SYSTEM_CARD_PROFILE_FIELDS.forEach(field=>{const el=document.getElementById(field.id); if(el)el.checked=field.key!=="safetyNotes"&&visibility[field.key]==="public";}); const members=document.getElementById("cardFieldMembers"); if(members)members.checked=false; const custom=document.getElementById("cardFieldMemberCustomFields"); if(custom)custom.checked=false; const box=document.getElementById("cardMemberBox"); if(box)box.style.display="none";}
    function selectedSystemCardNeedsConfirm(){const visibility=currentSystemProfileVisibility(); return SYSTEM_CARD_PROFILE_FIELDS.some(field=>{const checked=!!document.getElementById(field.id)?.checked; return checked&&(field.alwaysConfirm||visibility[field.key]!=="public");});}
    function confirmSystemCardDisclosure(){if(!selectedSystemCardNeedsConfirm())return true; return confirm("你选择加入的内容包含非公开字段。可见性只影响应用内导出和展示，不是加密隔离。确认加入系统名片吗？");}
    function renderSystemCardPanel(){const memberBox=document.getElementById("publicMemberList"), listBox=document.getElementById("externalSystemCardList"); syncSystemCardFieldDefaults(); if(memberBox){memberBox.innerHTML=data.members.length?data.members.map(m=>`<label class="public-member-row"><input type="checkbox" value="${esc(m.id)}" />${tagDot(m.tagId)}<span>${esc(m.name)}${m.role?` · ${esc(m.role)}`:""}</span></label>`).join(""):`<div class="empty">还没有${esc(term("member"))}。</div>`;} if(listBox){const rows=data.externalSystemCards||[]; listBox.innerHTML=rows.length?rows.map(x=>{const c=normalizeSystemCard(x.card); const idArg=jsAttrArg(x.id); return `<div class="relation-card"><div class="relation-title">${esc(c.systemName||`未命名${term("system")}`)}</div><div class="relation-type">${esc(c.collectiveName||"未填写集体称呼")} · ${new Date(x.receivedAt||now()).toLocaleString()}</div>${c.description?`<p>${esc(shortText(c.description,120))}</p>`:""}<div class="row"><button class="light small" type="button" onclick="viewExternalSystemCard(${idArg})">查看</button><button class="danger small" type="button" onclick="deleteExternalSystemCard(${idArg})">删除</button></div></div>`;}).join(""):`<div class="empty">还没有保存外部${esc(term("system"))}名片。</div>`;}}
    function selectedCardPayload(){const p={...blankSystemProfile(),...(data.systemProfile||{})}; const get=id=>!!document.getElementById(id)?.checked; const includeMemberCustom=get("cardFieldMemberCustomFields"); const publicMembers=get("cardFieldMembers")?[...document.querySelectorAll("#publicMemberList input:checked")].map(i=>member(i.value)).filter(Boolean).map(m=>({name:m.name||"",role:m.role||"",customFields:includeMemberCustom?systemCardPublicCustomFields(m):[]})):[]; const card=normalizeSystemCard({createdAt:now(),systemName:get("cardFieldSystemName")?p.systemName:"",collectiveName:get("cardFieldCollectiveName")?p.collectiveName:"",systemTypeText:get("cardFieldSystemTypeText")?p.systemTypeText:"",description:get("cardFieldDescription")?p.description:"",boundaries:get("cardFieldBoundaries")?p.boundaries:"",comfortMethods:get("cardFieldComfortMethods")?p.comfortMethods:"",safetyNotes:get("cardFieldSafetyNotes")?p.safetyNotes:"",publicMembers}); return {type:"moon-system-card",schemaVersion:1,createdAt:card.createdAt,card:{systemName:card.systemName,collectiveName:card.collectiveName,systemTypeText:card.systemTypeText,description:card.description,boundaries:card.boundaries,comfortMethods:card.comfortMethods,safetyNotes:card.safetyNotes,publicMembers:card.publicMembers}};}
    function drawQr(ctx,text,x,y,w){
      if(typeof qrcode!=="function")throw new Error("qr_library_missing");
      const qr=qrcode(0,"M");
      qr.addData(String(text||""));
      qr.make();
      const n=qr.getModuleCount(), quiet=4;
      const cell=Math.max(1,Math.floor(w/(n+quiet*2)));
      const real=cell*(n+quiet*2), ox=x+Math.floor((w-real)/2);
      ctx.fillStyle="#fff";
      ctx.fillRect(ox,y,real,real);
      ctx.fillStyle="#111827";
      for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(qr.isDark(r,c))ctx.fillRect(ox+(c+quiet)*cell,y+(r+quiet)*cell,cell,cell);
      return real;
    }
    function loadImageDataUrl(src){return new Promise((ok,fail)=>{if(!src){ok(null);return;} const img=new Image(); img.onload=()=>ok(img); img.onerror=fail; img.src=src;});}
    function coverDrawImage(ctx,img,w,h){const scale=Math.max(w/img.width,h/img.height), iw=img.width*scale, ih=img.height*scale; ctx.drawImage(img,(w-iw)/2,(h-ih)/2,iw,ih);}
    async function buildSystemCardImage(payload){const text=JSON.stringify(payload); const card=normalizeSystemCard({...payload.card,createdAt:payload.createdAt}); const mode=document.getElementById("cardImageMode")?.value||"qr"; const custom=document.getElementById("cardCustomText")?.value.trim()||""; const bgColor=document.getElementById("cardBgColor")?.value||"#f7f8fb"; const canvas=document.createElement("canvas"); canvas.width=1080; canvas.height=1440; const ctx=canvas.getContext("2d"); ctx.fillStyle=bgColor; ctx.fillRect(0,0,canvas.width,canvas.height); const bg=await loadImageDataUrl(pendingSystemCardBg); if(bg){ctx.globalAlpha=.92; coverDrawImage(ctx,bg,canvas.width,canvas.height); ctx.globalAlpha=1; ctx.fillStyle="rgba(255,255,255,.68)"; ctx.fillRect(0,0,canvas.width,canvas.height);} if(mode==="qr"){drawQr(ctx,text,170,260,740); return canvas.toDataURL("image/png");} ctx.fillStyle="#111827"; ctx.font="700 52px system-ui,-apple-system,BlinkMacSystemFont,sans-serif"; ctx.fillText("系统名片",78,118); ctx.font="26px system-ui,-apple-system,BlinkMacSystemFont,sans-serif"; ctx.fillStyle="#4b5563"; const body=mode==="custom"?custom:[`系统名称：${card.systemName||"未公开"}`,`集体称呼：${card.collectiveName||"未公开"}`,card.description?`简介：${shortText(card.description,120)}`:"",card.boundaries?`沟通边界：${shortText(card.boundaries,120)}`:"",`公开成员：${card.publicMembers.length} 位`].filter(Boolean).join("\n"); wrapCanvasText(ctx,body||"这张名片只包含二维码中的公开资料。",78,180,620,36); drawQr(ctx,text,300,820,480); ctx.fillStyle="#6b7280"; ctx.font="20px system-ui,-apple-system,BlinkMacSystemFont,sans-serif"; ctx.fillText("由《月之暗面》生成，仅包含用户选择公开的信息",78,1370); return canvas.toDataURL("image/png");}
    function wrapCanvasText(ctx,text,x,y,maxW,lineH){String(text||"").split("\n").forEach(part=>{let line=""; for(const ch of part){const test=line+ch; if(ctx.measureText(test).width>maxW&&line){ctx.fillText(line,x,y); y+=lineH; line=ch;} else line=test;} if(line){ctx.fillText(line,x,y); y+=lineH;}});}
    async function makeSystemCardImage(){if(!confirmSystemCardDisclosure())return null; const payload=selectedCardPayload(), text=JSON.stringify(payload); if(!payload.card.systemName&&!payload.card.collectiveName&&!payload.card.systemTypeText&&!payload.card.description&&!payload.card.boundaries&&!payload.card.comfortMethods&&!payload.card.safetyNotes&&!payload.card.publicMembers.length){alert("请至少公开一个可识别的信息。");return null;} if(new TextEncoder().encode(text).length>1800){alert("系统名片内容太长，二维码放不下。请减少公开字段、缩短简介/边界，或减少公开成员数量。");return null;} try{pendingSystemCardPayload=payload; const url=await buildSystemCardImage(payload); pendingSystemCardImage=url; document.getElementById("systemCardPreview").innerHTML=`<img src="${url}" alt="系统名片预览" />`; const a=document.getElementById("systemCardDownloadLink"); a.href=url; a.download=`月之暗面-系统名片-${new Date().toISOString().slice(0,10)}.png`; a.onclick=event=>{if(window.MoonAndroidDownloads&&window.downloadDataUrlFile){event.preventDefault(); saveSystemCardImage();}}; a.style.display="inline-block"; document.getElementById("systemCardCodeInput").value=text; return url;}catch(err){alert(err?.message==="qr_library_missing"?"二维码库未加载，请确认本地文件完整。":"生成二维码失败，请减少公开内容后再试。"); return null;}}
    async function saveSystemCardImage(){const url=pendingSystemCardImage||await makeSystemCardImage(); if(!url)return; const filename=`月之暗面-系统名片-${new Date().toISOString().slice(0,10)}.png`; if(window.downloadDataUrlFile){await window.downloadDataUrlFile(filename,"image/png",url); return;} if(window.MoonBridge?.saveDataUrlFile){window.MoonBridge.saveDataUrlFile(filename,"image/png",url); return;} const a=document.getElementById("systemCardDownloadLink"); a.click();}
    async function parseSystemCardImage(file){
      if(!file)return;
      try{
        const raw=await new Promise((ok,fail)=>{const r=new FileReader(); r.onload=()=>ok(String(r.result||"")); r.onerror=fail; r.readAsDataURL(file);});
        const img=await new Promise((ok,fail)=>{const im=new Image(); im.onload=()=>ok(im); im.onerror=fail; im.src=raw;});
        const c=document.createElement("canvas");
        const scale=Math.min(1,1800/Math.max(img.width,img.height));
        c.width=Math.max(1,Math.round(img.width*scale));
        c.height=Math.max(1,Math.round(img.height*scale));
        const ctx=c.getContext("2d",{willReadFrequently:true});
        ctx.drawImage(img,0,0,c.width,c.height);
        let value="";
        if("BarcodeDetector" in window){
          try{
            const detector=new BarcodeDetector({formats:["qr_code"]});
            const hits=await detector.detect(c);
            value=hits[0]?.rawValue||"";
          }catch(err){value="";}
        }
        if(!value&&typeof jsQR==="function"){
          const imageData=ctx.getImageData(0,0,c.width,c.height);
          const hit=jsQR(imageData.data,imageData.width,imageData.height,{inversionAttempts:"attemptBoth"});
          value=hit?.data||"";
        }
        if(!value){alert("没有在图片中识别到二维码。请使用“粘贴名片码”兜底。");return;}
        parseSystemCardCode(value,"qr-image");
      }catch(err){
        alert("识别二维码失败。请使用“粘贴名片码”兜底。");
      }
    }
    function parseSystemCardCode(value,source="manual"){try{const parsed=JSON.parse(String(value||"")); if(parsed.type!=="moon-system-card"){alert("这不是月之暗面的系统名片二维码。");return;} const card=normalizeSystemCard({...parsed.card,createdAt:parsed.createdAt}); pendingReceivedSystemCard={source,card}; showReceivedSystemCard(card);}catch{alert("名片码无法解析。请确认复制的是完整系统名片 JSON。");}}
    function systemCardHtml(card){const c=normalizeSystemCard(card); const memberText=c.publicMembers.map(m=>{const base=esc(`${m.name}${m.role?`（${m.role}）`:""}`); const fields=(m.customFields||[]).length?`：${m.customFields.map(f=>`${esc(f.name)}=${esc(f.value)}`).join("；")}`:""; return base+fields;}).join("、"); return `<div class="relation-title">${esc(c.systemName||"未命名系统")}</div><div class="relation-type">${esc(c.collectiveName||"未填写集体称呼")} ${c.systemTypeText?`· ${esc(c.systemTypeText)}`:""}</div>${c.description?`<p><strong>简介：</strong>${esc(c.description)}</p>`:""}${c.boundaries?`<p><strong>沟通边界：</strong>${esc(c.boundaries)}</p>`:""}${c.comfortMethods?`<p><strong>安抚方式：</strong>${esc(c.comfortMethods)}</p>`:""}${c.safetyNotes?`<p><strong>安全提醒：</strong>${esc(c.safetyNotes)}</p>`:""}${memberText?`<p><strong>公开成员：</strong>${memberText}</p>`:""}`;}
    function showReceivedSystemCard(card){document.getElementById("receivedSystemCardPreview").innerHTML=systemCardHtml(card); document.getElementById("saveExternalSystemCardBtn").style.display=pendingReceivedSystemCard?"inline-block":"none"; openModal("systemCardPreviewModal");}
    async function saveReceivedSystemCard(){if(!pendingReceivedSystemCard){closeModal("systemCardPreviewModal");return;} data.externalSystemCards=data.externalSystemCards||[]; data.externalSystemCards.push({id:makeId(),source:pendingReceivedSystemCard.source,receivedAt:now(),card:normalizeSystemCard(pendingReceivedSystemCard.card)}); if(await save()){pendingReceivedSystemCard=null; closeModal("systemCardPreviewModal"); renderSystemCardPanel(); alert("已保存为外部系统名片。");}}
    window.viewExternalSystemCard=function(id){const row=(data.externalSystemCards||[]).find(x=>x.id===id); if(!row)return; pendingReceivedSystemCard=null; showReceivedSystemCard(row.card);};
    window.deleteExternalSystemCard=async function(id){const row=(data.externalSystemCards||[]).find(x=>x.id===id); if(!row)return; if(!confirm(`确定删除外部系统名片「${normalizeSystemCard(row.card).systemName||"未命名系统"}」吗？`))return; data.externalSystemCards=(data.externalSystemCards||[]).filter(x=>x.id!==id); if(await save())renderSystemCardPanel();};
